### ISSUE TITLE
How do I get at the locales?

### ISSUE THREAD

**Issue by ScoreUnder** [mengxiong10/date-format-parse#17]
There are multiple locales available in `src/locale`, but accessing any of them isn't documented.

I have tried:

```ts
import locale from "date-format-parse/locale/en"
```

but this doesn't seem to work: `error TS2307: Cannot find module 'date-format-parse/locale/en' or its corresponding type declarations.`

**Comment by mengxiong10** [comment]
```js
import af from 'date-format-parse/lib/locale/en';
// or
import af from 'date-format-parse/es/locale/en';


```

**Comment by ScoreUnder** [comment]
Thank you!
